services:
  # Ubuntu24.04
  devcontainer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: devcontainer_ubuntu
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: sleep infinity

volumes:
  vendor:
    driver: local
